// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPhrnxw6MHmZVqdjw5UbMxmxEMnN3zmI',
    appId: '1:1079581401900:web:24d9f5cdc8ee01446d0289',
    messagingSenderId: '1079581401900',
    projectId: 'insta-attend',
    authDomain: 'insta-attend.firebaseapp.com',
    storageBucket: 'insta-attend.firebasestorage.app',
    measurementId: 'G-C2M9NLTR0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi42k1_nndowecVL4ykYMaE-UXOYtZZoE',
    appId: '1:1079581401900:android:947ec5901dcf8da16d0289',
    messagingSenderId: '1079581401900',
    projectId: 'insta-attend',
    storageBucket: 'insta-attend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeLypEkx-T6ScCk925xwUQ7nQ4w1BuOs',
    appId: '1:1079581401900:ios:45d01486dd003b2a6d0289',
    messagingSenderId: '1079581401900',
    projectId: 'insta-attend',
    storageBucket: 'insta-attend.firebasestorage.app',
    iosBundleId: 'com.nextechvision.instaAttend',
  );
}
